### PR TITLE
rqt_graph

### PR DESCRIPTION
**Pull request by arjunnaru**
Oushing the ROS System Overview Files

### CODE REVIEW

**Review by patman77 — COMMENTED** [review]
in general, binary files coming from Mac Finder such as .DS_Store shouldn't be committed to a git branch.

**Review by patman77 — CHANGES_REQUESTED** [review]
please delete .DS_Store files, commit again and create a pull request.

**Comment by arjunnaru** [comment]
Sounds good pat. I will do that

**Comment by arjunnaru** [comment]
Made the Changes pat

**Pull request closed without merging**
