### PR TITLE
dbw_node_v1

### PR DESCRIPTION
**Pull request by yangydavid**
#1  Description
- Implemented `waypoint_updater.py`
- Implemented `dbw_node.py`
- Implemented `twister_controller.py`
- Implemented `tl_detected.py` --> directly reading traffic light signals from the simulator, bypassing the traffic light classifier. 

#2 Next Step 
- (Potential) improve the lateral controller's performance by either fine tuning the existing controller or implement some LQR/MPC optimal control algorithm. (remain open, would like to hear your opinion)

### CODE REVIEW

**Comment by patman77** [comment]
Well done. Car follows the green line staying within lane. Car oscillates a little bit laterally. In the video walkthrough, I remember, they are talking about this at the end. We can keep that in mind (better PID, MPC etc.), but for the moment, we agreed on not doing it too fancy.

**Review by patman77 — APPROVED** [review]
Well done. Car follows the green line staying within lane. Car oscillates a little bit laterally. In the video walkthrough, I remember, they are talking about this at the end. We can keep that in mind (better PID, MPC etc.), but for the moment, we agreed on not doing it too fancy.

**Comment by alex4men** [comment]
Cool! It works!!! Though on Parallels VM I got some accidents, perhaps due to CPU overload.

**Review by alex4men — COMMENTED** [review]
Cool! It works!!! Though on Parallels VM I got some accidents, perhaps due to CPU overload.

**Review by alex4men — COMMENTED** [review]
Cool! It works!!! Though on Parallels VM I got some accidents, perhaps due to CPU overload.

**Pull request merged**
